#include <iostream>
#include <vector>
using namespace std;

/*
PROBLEM STATEMENT:

For example: 
Input Matrix: [ [ 1, 2, 3 ] 
                [ 4, 5, 6 ] 
                [ 7, 8, 9 ] ]

Output Matrix: [ [ 4, 1, 2 ] 
                 [ 7, 5, 3 ] 
                 [ 8, 9, 6 ] ]

The output matrix is generated by rotating the elements of the input matrix in a clockwise direction. 
Note that every element is rotated only once.
*/
void rotateMatrix(vector<vector<int> > &matrix, int n, int m)
{
    int rowS=0, colS=0, rowE=n-1, colE=m-1;
    int prev;
    if(n==1 || m==1)
    {
        return;
    }
    while(rowS<rowE && colS<colE)
    {
        if(rowS<rowE) prev=matrix[rowS+1][colS];
        //left to right
        for(int i=colS; i<=colE; i++)
        {
            int current = matrix[rowS][i];
            matrix[rowS][i] = prev;
            prev = current;
        }
        rowS++;
        
        //top to bottom
        for(int i=rowS; i<=rowE; i++)
        {
            int current = matrix[i][colE];
            matrix[i][colE] = prev;
            prev = current;
        }
        colE--;

        //right to left
        for(int i=colE; i>=colS; i--)
        {
            int current = matrix[rowE][i];
            matrix[rowE][i] = prev;
            prev = current;
        }
        rowE--;
        //bottom to top
        for(int i=rowE; i>=rowS; i--)
        {
            int current = matrix[i][colS];
            matrix[i][colS] = prev;
            prev = current;
        }
        colS++;
    }
}
int main()
{
    int n, m;
    cin>>n>>m;
    vector<vector<int> > matrix;
    for(int i=0; i<n; i++)
    {
        vector<int> row;
        int val;
        for(int j=0; j<m; j++)
        {
            cin>>val;
            row.push_back(val);
        }
        matrix.push_back(row);
    }

    rotateMatrix(matrix, n, m);

    //print matrix
    for(int i=0; i<n; i++)
    {
        for(int j=0; j<m; j++)
        {
            cout<<matrix[i][j]<<" ";
        }
        cout<<endl;
    }
}
